# Generated by Django 3.2.6 on 2021-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20210808_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('lodging', 'Lodging'), ('food', 'Food'), ('trans', 'transportation'), ('ticket', 'Ticket'), ('grocery', 'Grocery'), ('other', 'Other')], max_length=10),
        ),
    ]
