# Generated by Django 3.2.6 on 2021-08-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file',
            field=models.FileField(default='file', upload_to='receipt-upload'),
        ),
    ]
