# Generated by Django 3.2.6 on 2021-08-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20210814_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(default='file', upload_to='receipts/'),
        ),
    ]
