# Generated by Django 3.2.6 on 2021-08-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expense_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
