# Generated by Django 3.2.6 on 2021-08-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_expense_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
