# Generated by Django 3.2.6 on 2021-08-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_expense_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='total_cost',
        ),
    ]
