# Generated by Django 3.2.6 on 2021-08-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_auto_20210816_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
