# Generated by Django 3.2.6 on 2021-08-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
