# Generated by Django 3.2.6 on 2021-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20210809_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='c_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
