# Generated by Django 3.2.6 on 2021-08-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_trip_c_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='c_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
